name: Build, Test & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build & Test  # Combine build and test steps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Test step removed

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build

  merge-and-test:
    name: Merge Pull Request & Test  # Combine merge and test steps
    needs: [build]
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Merge pull request
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout -b merge
          git merge --no-ff --no-commit ${{ github.event.pull_request.head.ref }}
          git commit -m "Merge pull request #${{ github.event.pull_request.number }}"

      - name: Push changes
        run: git push origin merge

  deploy:
    name: Deploy  # Corrected indentation (same level as 'build' and 'merge-and-test')
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build
      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./build/  # Ensure it ends with a slash
          server-dir: /poc/   # Ensure it ends with a slash
